### ISSUE TITLE
DateTimeRange OverFlow

### ISSUE THREAD

**Issue by satyap2436** [jja08111/time_chart#15]
Y-axis times slots are creating problem and hence while plotting graphs data is overflowing(Jumping to next day).

**Comment by jja08111** [comment]
Hi @satyap2436, thanks for filling the issue.

Can you provide sample data for reproducing the issue?

**Comment by satyap2436** [comment]
![timechartgraph](https://user-images.githubusercontent.com/44051649/145670517-56aba583-f88c-4904-8093-5a58050b29c3.png)

Today is saturday but the graph generated is showing in sunday column, Please have look.

**Comment by jja08111** [comment]
@satyap2436 Thanks for adding more information.

This is not overflowing because the bars are upper the **0 AM (start of the day)**.
![스크린샷 2021-12-11 오후 6 22 01](https://user-images.githubusercontent.com/57604817/145671607-0e1b6563-b72e-4cc5-8cb9-43cfecfce690.png)

The reason is because of the chart drawing algorithm that finds max widely empty hour duration for setting the top hour and bottom hour.

**Comment by satyap2436** [comment]
@jja08111 Thanks for providing information.

could you please tell how to fix this for now ? or anyway we can change the label of y - axis(right side from 1 to 24 hour format so that it draws the graph properly.

any idea when we gonna get the next release.

**Comment by jja08111** [comment]
Unfortunately, there is no way to fix it.

I will change the package to set the right side from 0 to 24 hour format when data has no empty hours. 

But, I'm very busy until the next week. After that, I will fix the issue. Thanks.

**Comment by satyap2436** [comment]
@jja08111 Thank you very much, waiting for update, Once package update just let me know.

**Comment by jja08111** [comment]
Hi @satyap2436, 

I've added `defaultPivotHour` parameter in dev branch. Can you test the branch if that is working as you expected?
```yaml
time_chart:
    git:
      url: https://github.com/jja08111/time_chart.git
      ref: dev
```

**Comment by satyap2436** [comment]
Thanks @jja08111 , Now its working fine.
