### ISSUE TITLE
Failed to Process Time Difference in second

### ISSUE THREAD

**Issue by satyap2436** [jja08111/time_chart#20]
![image](https://user-images.githubusercontent.com/44051649/147930555-5051338f-b7b4-42ea-a9ae-9fe541dec53d.png)

The data list is reversed or not sorted. Check the data parameter. The first data must be newest data.
'package:time_chart/src/components/utils/time_data_processor.dart':
Failed assertion: line 133 pos 16: 'dataList[i - 1].end.isAfter(dataList[i].end)'

check the record 174 & 175(similar other records) , there is difference in seconds but i m getting the above error.

**Comment by jja08111** [comment]
Hi @satyap2436, thanks for filling the issue again.

I think your data is reversed. I fixed the plugin assertion after the version `0.3.0`. 
How about reversing data and testing? The first index data is the newest data, the last index data is the oldest data.
For example,
```dart
assert(data[0].isAfter(data[1])) // true
```
