### ISSUE TITLE
Can you give me a demo that looks exactly like this picture? Is it misleading?

### ISSUE THREAD

**Issue by ssh199956** [jja08111/time_chart#38]
I noticed that your weekly time chart cannot be scrolled up and down, but the picture is OK. Is there any setting required for this? Can you give me a demo that is exactly the same as this picture? Otherwise it will be misleading.
Here is your original picture.
https://github.com/jja08111/time_chart/blob/main/assets/images/time_chart/weekly_time_chart.gif?raw=true

**Comment by jja08111** [comment]
Hi @ssh199956, sorry for late. The vertical scrolling automatically starts when the start time and the end time are different with before scrolling. Example data is [here](https://github.com/jja08111/time_chart#3---usage). Thanks.
